services:
  todo-list-standalone:
    image: ghcr.io/mcesarczyk/timely-todo-list-standalone:latest
    ports:
      - 3010:8080
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    expose:
      - 3010
    networks:
      - timely_default

networks:
  timely_default:
    external: true
