services:
  todo-list-standalone:
    container_name: timely-todo-list-standalone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3033:8080
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://timely-api:4000
    env_file:
      - .env.production
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    expose:
      - 3033
    networks:
      - compose_timely-frontend

networks:
  compose_timely-frontend:
    external: true
